# full-automation.yml
#
# Description: Complete automation playbook for worker VM setup and creation
#
# This Ansible playbook provides end-to-end automation for setting up worker VMs
# in the distributed VM system. It combines system preparation, Docker installation,
# and VM creation into a single automated workflow.
#
# Inputs: None (uses localhost as target)
# Outputs:
#   - Docker installed and configured
#   - Aleph node image pulled
#   - Repository cloned
#   - New VM created with specified configuration
#
# Prerequisites:
#   - Ansible installed
#   - KVM/QEMU available
#   - virt-install command available
#   - sudo privileges

---
- name: Full Automation for Worker VM Setup
  hosts: localhost
  tasks:
    - name: Run Worker VM Setup Script
      shell: |
        sudo apt update && sudo apt install -y docker.io
        sudo systemctl start docker && sudo systemctl enable docker
        sudo docker pull aleph/node
        git clone https://github.com/jw-wcv/dist-vm-system.git ~/distributed-compute

    - name: Create VM
      command: >
        virt-install \
        --name aleph-vm \
        --vcpus 4 \
        --memory 8192 \
        --disk size=80 \
        --os-variant ubuntu20.04 \
        --network bridge=virbr0 \
        --graphics none \
        --console pty,target_type=serial
