# setup.yml
#
# Description: Main setup playbook for worker VMs in the distributed system
#
# This is the primary Ansible playbook for initializing worker nodes in the
# distributed VM system. It performs the core setup tasks including Docker
# installation, repository cloning, and VM creation using KVM.
#
# Inputs:
#   - Target hosts: workers (defined in inventory)
#   - Repository URL: https://github.com/jw-wcv/dist-vm-system.git
# Outputs:
#   - Docker installed on worker nodes
#   - Repository cloned to ~/distributed-compute directory
#   - New VM created with KVM (4 vCPUs, 8GB RAM, 80GB disk)
#
# Prerequisites:
#   - Ansible inventory with 'workers' group defined
#   - SSH access to worker nodes
#   - KVM/QEMU available on worker nodes
#   - sudo privileges on worker nodes
#   - Internet connectivity for package installation and git cloning

- name: Setup Worker VMs
  hosts: workers
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Clone Distributed Compute Repo
      git:
        repo: "https://github.com/jw-wcv/dist-vm-system.git"
        dest: ~/distributed-compute

    - name: Create VM using KVM
      command: >
        virt-install \
        --name aleph-vm \
        --vcpus 4 \
        --memory 8192 \
        --disk size=80 \
        --os-variant ubuntu20.04 \
        --network bridge=virbr0 \
        --graphics none \
        --console pty,target_type=serial
