- name: Setup Worker VMs
  hosts: workers
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Clone Distributed Compute Repo
      git:
        repo: 'https://github.com/jw-wcv/dist-vm-system.git'
        dest: ~/distributed-compute