# worker-setup.yml
#
# Description: Ansible playbook for setting up worker VMs in the distributed system
#
# This playbook automates the configuration of worker nodes in the distributed VM
# system. It installs Docker, clones the necessary repository, and creates VMs
# using KVM virtualization.
#
# Inputs:
#   - Target hosts: workers (defined in inventory)
#   - Repository URL for cloning
# Outputs:
#   - Docker installed on worker nodes
#   - Repository cloned to ~/distributed-compute
#   - New VM created with KVM configuration
#
# Prerequisites:
#   - Ansible inventory with 'workers' group defined
#   - SSH access to worker nodes
#   - KVM/QEMU available on worker nodes
#   - sudo privileges on worker nodes

---
- name: Setup Worker VMs
  hosts: workers
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Clone Distributed Compute Repo
      git:
        repo: "https://github.com/jw-wcv/dist-vm-system.git"
        dest: ~/distributed-compute

    - name: Create VM using KVM
      command: >
        virt-install \
        --name aleph-vm \
        --vcpus 4 \
        --memory 8192 \
        --disk size=80 \
        --os-variant ubuntu20.04 \
        --network bridge=virbr0 \
        --graphics none \
        --console pty,target_type=serial
